services:
  - type: web
    name: multimedia-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn multimedia_app.wsgi:application"
    runtime: python
    pythonVersion: 3.11.9
    envVars:
      - key: DATABASE_URL
        sync: false
